name: Sync multiple branches
on:
  push:
    branches:
      -  '*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0

        with:
          source_ref: release/v1
          target_branch: develop
          github_token: ${{ github.token }}
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
