name: Follow Branch
on: 
  pull_request:
    branches: 
      - develop
    types: [closed]

jobs:
  run_action:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Merge Follow Branch
        uses: toysmoon/follow_branch@1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: emailDev
          following-branch: develop
